============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.4.3, pluggy-1.3.0 -- /Users/gasparburgi/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/gasparburgi/code/GasparinB/07-ML-Ops/01-Train-at-scale/data-train-at-scale/tests
configfile: pytest_kitt.ini
collecting ... collected 8 items

tests/train_at_scale/test_clean.py::test_clean_data PASSED               [ 12%]
tests/train_at_scale/test_main_local.py::TestMainLocal::test_route_preprocess_and_train PASSED [ 25%]
tests/train_at_scale/test_main_local.py::TestMainLocal::test_route_pred PASSED [ 37%]
tests/train_at_scale/test_main_local.py::TestMainLocal::test_route_preprocess FAILED [ 50%]
tests/train_at_scale/test_main_local.py::TestMainLocal::test_route_train PASSED [ 62%]
tests/train_at_scale/test_model.py::test_model_can_fit PASSED            [ 75%]
tests/train_at_scale/test_notebook.py::TestNotebook::test_y_pred PASSED  [ 87%]
tests/train_at_scale/test_processor_pipeline.py::test_preprocess_features PASSED [100%]

=================================== FAILURES ===================================
_____________________ TestMainLocal.test_route_preprocess ______________________

self = <tests.train_at_scale.test_main_local.TestMainLocal object at 0x121ca7cd0>
fixture_query_1k =      fare_amount           pickup_datetime  ...  dropoff_latitude  passenger_count
0            8.9 2009-01-15 09:22:3...           4
454          8.5 2014-12-27 16:47:42+00:00  ...         40.771263                4

[455 rows x 7 columns]
fixture_processed_1k =            0    1    2    3    4    5   ...   60   61   62   63   64         65
0    0.000000  0.0  0.0  0.0  1.0  0.0...0.0   6.500000
446  0.428571  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   8.500000

[447 rows x 66 columns]

    def test_route_preprocess(self, fixture_query_1k: pd.DataFrame, fixture_processed_1k: pd.DataFrame):
        from taxifare.interface.main_local import preprocess
    
        data_query_path = Path(LOCAL_DATA_PATH).joinpath("raw",f"query_{MIN_DATE}_{MAX_DATE}_{DATA_SIZE}.csv")
        data_processed_path = Path(LOCAL_DATA_PATH).joinpath("processed",f"processed_{MIN_DATE}_{MAX_DATE}_{DATA_SIZE}.csv")
    
        data_query_exists = data_query_path.is_file()
        data_processed_exists = data_processed_path.is_file()
    
        # SETUP
        if data_query_exists:
            shutil.copyfile(data_query_path, f'{data_query_path}_backup')
            data_query_path.unlink()
        if data_processed_exists:
            shutil.copyfile(data_processed_path, f'{data_processed_path}_backup')
            data_processed_path.unlink()
    
        # ACT
        # Check route runs querying Big Query
>       preprocess(min_date=MIN_DATE, max_date=MAX_DATE)

tests/train_at_scale/test_main_local.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
taxifare/interface/main_local.py:179: in preprocess
    chunk_processed.to_csv(data_processed_path,mode='w' if chunk_id==0 else 'a',header=False,index=False)
taxifare/interface/main_local.py:179: in preprocess
    chunk_processed.to_csv(data_processed_path,mode='w' if chunk_id==0 else 'a',header=False,index=False)
../../../../../.pyenv/versions/3.10.6/lib/python3.10/bdb.py:90: in trace_dispatch
    return self.dispatch_line(frame)
../../../../../.pyenv/versions/3.10.6/lib/python3.10/bdb.py:114: in dispatch_line
    self.user_line(frame)
../../../../../.pyenv/versions/3.10.6/lib/python3.10/pdb.py:262: in user_line
    self.interaction(frame, None)
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/IPython/core/debugger.py:455: in interaction
    OldPdb.interaction(self, frame, tb)
../../../../../.pyenv/versions/3.10.6/lib/python3.10/pdb.py:357: in interaction
    self._cmdloop()
../../../../../.pyenv/versions/3.10.6/lib/python3.10/pdb.py:322: in _cmdloop
    self.cmdloop()
../../../../../.pyenv/versions/3.10.6/lib/python3.10/cmd.py:126: in cmdloop
    line = input(self.prompt)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.capture.DontReadFromInput object at 0x104037790>, size = -1

    def read(self, size: int = -1) -> str:
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/_pytest/capture.py:202: OSError
----------------------------- Captured stdout call -----------------------------
[35m
 ⭐️ Use case: preprocess by batch[0m
Get a dataframe iterable from Querying Big Query server...
processing chunk 0...
✅ data cleaned
clean_data executed in 0.02 seconds, using up to 0.06MB of RAM
[34m
Preprocessing features...[0m
✅ X_processed, with shape (253, 65)
preprocess_features executed in 0.09 seconds, using up to 0.39MB of RAM
> [0;32m/Users/gasparburgi/code/GasparinB/07-ML-Ops/01-Train-at-scale/data-train-at-scale/taxifare/interface/main_local.py[0m(179)[0;36mpreprocess[0;34m()[0m
[0;32m    178 [0;31m        [0mbreakpoint[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m--> 179 [0;31m        [0mchunk_processed[0m[0;34m.[0m[0mto_csv[0m[0;34m([0m[0mdata_processed_path[0m[0;34m,[0m[0mmode[0m[0;34m=[0m[0;34m'w'[0m [0;32mif[0m [0mchunk_id[0m[0;34m==[0m[0;36m0[0m [0;32melse[0m [0;34m'a'[0m[0;34m,[0m[0mheader[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m[0mindex[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m    180 [0;31m[0;34m[0m[0m
[0m
ipdb> 
=========================== short test summary info ============================
FAILED tests/train_at_scale/test_main_local.py::TestMainLocal::test_route_preprocess
================== 1 failed, 7 passed, 118 warnings in 20.07s ==================
